// vue-chat/src/App.vue
<script setup lang="ts">
import { useChat } from "./composables/useChat";
import { useChatStore } from "./store/chatStore";

import Login from "./components/Login.vue";
import ConnectionStatus from "./components/ConnectionStatus.vue";
import MessageList from "./components/MessageList.vue";
import MessageInput from "./components/MessageInput.vue";

const chatStore = useChatStore();

useChat();
</script>

<template>
  <div class="ambient-orb orb-1"></div>
  <div class="ambient-orb orb-2"></div>

  <Login v-if="!chatStore.user" />

  <div v-else class="outer-shell">
    <div class="chat-app">
      <div class="chat-container">
        <header class="chat-header">
          <h1>Chat Realtime Vue 3</h1>
          <ConnectionStatus />
        </header>

        <main class="chat-main">
          <MessageList />
        </main>

        <footer class="chat-footer">
          <MessageInput />
        </footer>
      </div>
    </div>
  </div>
</template>

// react-chat/src/App.tsx
import { useChat } from "./hooks/useChat";
import { useChatStore } from "./store/chatStore";
import { Login } from "./components/Login";
import { ConnectionStatus } from "./components/ConnectionStatus";
import { MessageList } from "./components/MessageList";
import { MessageInput } from "./components/MessageInput";
import "./index.css";

function App() {
  const user = useChatStore((state) => state.user);

  useChat();

  return (
    <>
      <div className="ambient-orb orb-1"></div>
      <div className="ambient-orb orb-2"></div>

      {!user ? (
        <Login />
      ) : (
        <div className="outer-shell">
          <div className="chat-app">
            <div className="chat-container">
              <header className="chat-header">
                <h1>Chat Realtime React</h1>
                <ConnectionStatus />
              </header>

              <main className="chat-main">
                <MessageList />
              </main>

              <footer className="chat-footer">
                <MessageInput />
              </footer>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

export default App;
