// vue-chat/src/components/ConnectionStatus.vue
<script setup lang="ts">
import { useChatStore } from '../store/chatStore';

const chatStore = useChatStore();
</script>

<template>
  <div class="status-bar">
    <div class="status-indicator">
      Status: {{ chatStore.connected ? '🟢 Conectado' : '🔴 Desconectado' }}
    </div>
    <div v-if="chatStore.user" class="user-info">
      <img :src="chatStore.user.avatar" alt="avatar" class="avatar-small" />
      <span class="username">{{ chatStore.user.username }}</span>
      <button @click="chatStore.logout" class="logout-btn" title="Cerrar sesión">Salir</button>
    </div>
  </div>
</template>

// react-chat/src/components/ConnectionStatus.tsx
import { useChatStore } from '../store/chatStore';

export function ConnectionStatus() {
  const { connected, user, logout } = useChatStore();

  return (
    <div className="status-bar">
      <div className="status-indicator">
        Status: {connected ? '🟢 Conectado' : '🔴 Desconectado'}
      </div>
      {user && (
        <div className="user-info">
          <img src={user.avatar} alt="avatar" className="avatar-small" />
          <span className="username">{user.username}</span>
          <button onClick={logout} className="logout-btn" title="Cerrar sesión">Salir</button>
        </div>
      )}
    </div>
  );
}
