// vue-chat/src/components/MessageItem.vue
<script setup lang="ts">
import type { ChatMessage } from "../types/chat";
import { formatTime } from "../utils/formatTime";
import Avatar from "./Avatar.vue";

defineProps<{
  message: ChatMessage;
  isOwn: boolean;
}>();
</script>

<template>
  <div
    :class="['message-item', isOwn ? 'own-message' : 'other-message']"
  >
    <Avatar
      v-if="!isOwn"
      :src="message.avatar"
      :alt="message.sender"
    />
    <div class="message-bubble">
      <div v-if="!isOwn" class="message-sender">{{ message.sender }}</div>
      <div class="message-text">{{ message.text }}</div>
      <div class="message-time">{{ formatTime(message.timestamp) }}</div>
    </div>
  </div>
</template>

// react-chat/src/components/MessageItem.tsx
import type { ChatMessage } from "../types/chat";
import { formatTime } from "../utils/formatTime";
import { Avatar } from "./Avatar";

interface MessageItemProps {
  message: ChatMessage;
  isOwn: boolean;
}

export function MessageItem({ message, isOwn }: MessageItemProps) {
  return (
    <div
      className={`message-item ${isOwn ? "own-message" : "other-message"}`}
    >
      {!isOwn && (
        <Avatar src={message.avatar} alt={message.sender} />
      )}
      <div className="message-bubble">
        {!isOwn && <div className="message-sender">{message.sender}</div>}
        <div className="message-text">{message.text}</div>
        <div className="message-time">{formatTime(message.timestamp)}</div>
      </div>
    </div>
  );
}
