// vue-chat/src/components/MessageList.vue
<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import { useChatStore } from "../store/chatStore";

const chatStore = useChatStore();
const messagesEndRef = ref<HTMLDivElement | null>(null);

watch(
  () => chatStore.messages.length,
  async () => {
    await nextTick();
    if (messagesEndRef.value) {
      messagesEndRef.value.scrollIntoView({ behavior: "smooth" });
    }
  },
  { immediate: true },
);

const isOwnMessage = (sender: string) => {
  return sender === chatStore.user?.username;
};

const formatTime = (ts: number) => {
  return new Date(ts).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });
};
</script>

<template>
  <div class="message-list-container">
    <div v-if="chatStore.messages.length === 0" class="empty-chat">
      No hay mensajes. Sé el primero en decir hola.
    </div>

    <template v-else>
      <div
        v-for="msg in chatStore.messages"
        :key="msg.id"
        :class="[
          'message-item',
          isOwnMessage(msg.sender) ? 'own-message' : 'other-message',
        ]"
      >
        <img
          v-if="!isOwnMessage(msg.sender)"
          :src="msg.avatar"
          :alt="msg.sender"
          class="message-avatar"
        />

        <div class="message-bubble">
          <div v-if="!isOwnMessage(msg.sender)" class="message-sender">
            {{ msg.sender }}
          </div>
          <div class="message-text">{{ msg.text }}</div>
          <div class="message-time">{{ formatTime(msg.timestamp) }}</div>
        </div>
      </div>
    </template>

    <div ref="messagesEndRef"></div>
  </div>
</template>

// react-chat/src/components/MessageList.tsx
import { useEffect, useRef } from "react";
import { useChatStore } from "../store/chatStore";

export function MessageList() {
  const messages = useChatStore((state) => state.messages);
  const user = useChatStore((state) => state.user);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  return (
    <div className="message-list-container">
      {messages.length === 0 ? (
        <div className="empty-chat">
          No hay mensajes. Sé el primero en decir hola.
        </div>
      ) : (
        messages.map((msg) => {
          const isOwn = msg.sender === user?.username;
          return (
            <div
              key={msg.id}
              className={`message-item ${isOwn ? "own-message" : "other-message"}`}
            >
              {!isOwn && (
                <img
                  src={msg.avatar}
                  alt={msg.sender}
                  className="message-avatar"
                />
              )}
              <div className="message-bubble">
                {!isOwn && <div className="message-sender">{msg.sender}</div>}
                <div className="message-text">{msg.text}</div>
                <div className="message-time">
                  {new Date(msg.timestamp).toLocaleTimeString([], {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </div>
              </div>
            </div>
          );
        })
      )}
      <div ref={messagesEndRef} />
    </div>
  );
}
