// react-chat/src/components/Login.tsx
import { useState } from "react";
import { useChatStore } from "../store/chatStore";

export function Login() {
  const [username, setUsername] = useState("");
  const setUser = useChatStore((state) => state.setUser);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (username.trim()) {
      const avatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(username)}&background=random`;
      setUser({ username: username.trim(), avatar });
    }
  };

  return (
    <div className="login-container">
      <h2>Ingresar al Chat</h2>
      <form onSubmit={handleSubmit} className="login-form">
        <input
          type="text"
          placeholder="Tu nombre..."
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          required
          autoFocus
        />
        <button type="submit">Entrar</button>
      </form>
    </div>
  );
}

// vue-chat/src/components/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useChatStore } from "../store/chatStore";

const chatStore = useChatStore();
const username = ref("");

const handleSubmit = () => {
  if (username.value.trim()) {
    const avatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(username.value.trim())}&background=random`;
    chatStore.setUser({ username: username.value.trim(), avatar });
  }
};
</script>

<template>
  <div class="login-container">
    <h2>Ingresar al Chat</h2>
    <form @submit.prevent="handleSubmit" class="login-form">
      <input
        type="text"
        placeholder="Tu nombre..."
        v-model="username"
        required
        autofocus
      />
      <button type="submit">Entrar</button>
    </form>
  </div>
</template>
