// react-chat/src/components/MessageInput.tsx
import { useState } from "react";
import { socketService } from "../services/socket";
import { useChatStore } from "../store/chatStore";

export function MessageInput() {
  const [text, setText] = useState("");
  const user = useChatStore((state) => state.user);

  const handleSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (text.trim() && user) {
      const message = {
        id: crypto.randomUUID(),
        sender: user.username,
        avatar: user.avatar,
        text: text.trim(),
        timestamp: Date.now(),
      };

      socketService.sendMessage(message);
      setText("");
    }
  };

  return (
    <form className="message-input-form" onSubmit={handleSend}>
      <input
        type="text"
        placeholder="escribir mensaje..."
        value={text}
        onChange={(e) => setText(e.target.value)}
        autoFocus
      />
      <button type="submit" disabled={!text.trim()}>
        Enviar
      </button>
    </form>
  );
}

// vue-chat/src/components/MessageInput.vue
<script setup lang="ts">
import { ref } from "vue";
import { socketService } from "../services/socket";
import { useChatStore } from "../store/chatStore";

const chatStore = useChatStore();
const text = ref("");

const handleSend = () => {
  if (text.value.trim() && chatStore.user) {
    const message = {
      id: crypto.randomUUID(),
      sender: chatStore.user.username,
      avatar: chatStore.user.avatar,
      text: text.value.trim(),
      timestamp: Date.now(),
    };

    socketService.sendMessage(message);
    text.value = "";
  }
};
</script>

<template>
  <form class="message-input-form" @submit.prevent="handleSend">
    <input
      type="text"
      placeholder="escribir mensaje..."
      v-model="text"
      autofocus
    />
    <button type="submit" :disabled="!text.trim()">Enviar</button>
  </form>
</template>
